name: Test

on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Test local rust
        uses: Kristories/cargo-test@v1.0.0
